### ISSUE TITLE
Suggestions to improve the code for more display flexibility

### ISSUE THREAD

**Issue by ghost** [LunaTechsDev/Luna-game-pause#1]
In the current version of the plugin, the text area is not really centered in the window, and a bit too narrow to display long text. Here are some code improvements I could suggest.

**New plugins parameters**

@param pauseWidth
@text Pause Width
@default 100

@param pauseHeight
@text Pause Height
@default 75

**LunaScenePause.createPauseWindow() (line 112)**

createPauseWindow() {
        let params = LunaGamePause.params()
        this._pauseWindow = new LunaPauseWindow(Graphics.width / 2 - params.pauseWidth / 2,Graphics.height / 2 - params.pauseHeight / 2,params.pauseWidth,params.pauseHeight)
        this.addWindow(this._pauseWindow)
        this._pauseWindow.setPauseText(params.pauseText)
        this._pauseWindow.refresh()
    }

**LunaGamePause.main() (line 143)**

LunaGamePause.LGParams = { pauseButton : params["pauseButton"], pauseText : params["pauseText"], pauseWidth : params["pauseWidth"], pauseHeight : params["pauseHeight"] }

Note: issue reported first in the RMW forum [here](https://forums.rpgmakerweb.com/index.php?threads/lunatechs-mv-mz-plugins-tools.127082/page-2#post-1128908).

**Comment by KinoAR** [comment]
We resolved this and have made an update as per the above to improve the flexibility of the window!

**Comment by KinoAR** [comment]
See result here: https://github.com/LunaTechsDev/Luna-game-pause/commit/36bce3825414aad949360bbb229acfea53d18213
